schema: './schema.graphql'
extensions:
  codegen:
    overwrite: true
    documents: null
    generates:
      src/graphql.types.ts:
        config:
          skipTypename: true
          contextType: ./api/context#Context
          maybeValue: T | undefined
          defaultMapper: 'Partial<{T}>'
          mappers:
            User: ./services/users/model#User as UserModel
            UserMetadata: ./services/users/model#UserMetadata as UserMetadataModel
        plugins:
          - 'typescript'
          - 'typescript-resolvers'
          - 'typescript-document-nodes'
